// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: api/proto/mill/execution/v1/execution.proto

package executionv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AttemptState int32

const (
	AttemptState_ATTEMPT_STATE_UNSPECIFIED AttemptState = 0
	AttemptState_ATTEMPT_STATE_STARTING    AttemptState = 1
	AttemptState_ATTEMPT_STATE_RUNNING     AttemptState = 2
	AttemptState_ATTEMPT_STATE_COMPLETED   AttemptState = 3
	AttemptState_ATTEMPT_STATE_FAILED      AttemptState = 4
)

// Enum value maps for AttemptState.
var (
	AttemptState_name = map[int32]string{
		0: "ATTEMPT_STATE_UNSPECIFIED",
		1: "ATTEMPT_STATE_STARTING",
		2: "ATTEMPT_STATE_RUNNING",
		3: "ATTEMPT_STATE_COMPLETED",
		4: "ATTEMPT_STATE_FAILED",
	}
	AttemptState_value = map[string]int32{
		"ATTEMPT_STATE_UNSPECIFIED": 0,
		"ATTEMPT_STATE_STARTING":    1,
		"ATTEMPT_STATE_RUNNING":     2,
		"ATTEMPT_STATE_COMPLETED":   3,
		"ATTEMPT_STATE_FAILED":      4,
	}
)

func (x AttemptState) Enum() *AttemptState {
	p := new(AttemptState)
	*p = x
	return p
}

func (x AttemptState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AttemptState) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_mill_execution_v1_execution_proto_enumTypes[0].Descriptor()
}

func (AttemptState) Type() protoreflect.EnumType {
	return &file_api_proto_mill_execution_v1_execution_proto_enumTypes[0]
}

func (x AttemptState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AttemptState.Descriptor instead.
func (AttemptState) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_mill_execution_v1_execution_proto_rawDescGZIP(), []int{0}
}

type LeaseActiveAttemptsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Executor      string                 `protobuf:"bytes,1,opt,name=executor,proto3" json:"executor,omitempty"`
	LeaseOwner    string                 `protobuf:"bytes,2,opt,name=lease_owner,json=leaseOwner,proto3" json:"lease_owner,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaseActiveAttemptsRequest) Reset() {
	*x = LeaseActiveAttemptsRequest{}
	mi := &file_api_proto_mill_execution_v1_execution_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaseActiveAttemptsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaseActiveAttemptsRequest) ProtoMessage() {}

func (x *LeaseActiveAttemptsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_mill_execution_v1_execution_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaseActiveAttemptsRequest.ProtoReflect.Descriptor instead.
func (*LeaseActiveAttemptsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_mill_execution_v1_execution_proto_rawDescGZIP(), []int{0}
}

func (x *LeaseActiveAttemptsRequest) GetExecutor() string {
	if x != nil {
		return x.Executor
	}
	return ""
}

func (x *LeaseActiveAttemptsRequest) GetLeaseOwner() string {
	if x != nil {
		return x.LeaseOwner
	}
	return ""
}

type LeaseActiveAttemptsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Attempts      []*ClaimedAttempt      `protobuf:"bytes,1,rep,name=attempts,proto3" json:"attempts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaseActiveAttemptsResponse) Reset() {
	*x = LeaseActiveAttemptsResponse{}
	mi := &file_api_proto_mill_execution_v1_execution_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaseActiveAttemptsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaseActiveAttemptsResponse) ProtoMessage() {}

func (x *LeaseActiveAttemptsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_mill_execution_v1_execution_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaseActiveAttemptsResponse.ProtoReflect.Descriptor instead.
func (*LeaseActiveAttemptsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_mill_execution_v1_execution_proto_rawDescGZIP(), []int{1}
}

func (x *LeaseActiveAttemptsResponse) GetAttempts() []*ClaimedAttempt {
	if x != nil {
		return x.Attempts
	}
	return nil
}

type ClaimNextAttemptRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Executor      string                 `protobuf:"bytes,1,opt,name=executor,proto3" json:"executor,omitempty"`
	LeaseOwner    string                 `protobuf:"bytes,2,opt,name=lease_owner,json=leaseOwner,proto3" json:"lease_owner,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClaimNextAttemptRequest) Reset() {
	*x = ClaimNextAttemptRequest{}
	mi := &file_api_proto_mill_execution_v1_execution_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimNextAttemptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimNextAttemptRequest) ProtoMessage() {}

func (x *ClaimNextAttemptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_mill_execution_v1_execution_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimNextAttemptRequest.ProtoReflect.Descriptor instead.
func (*ClaimNextAttemptRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_mill_execution_v1_execution_proto_rawDescGZIP(), []int{2}
}

func (x *ClaimNextAttemptRequest) GetExecutor() string {
	if x != nil {
		return x.Executor
	}
	return ""
}

func (x *ClaimNextAttemptRequest) GetLeaseOwner() string {
	if x != nil {
		return x.LeaseOwner
	}
	return ""
}

type ClaimNextAttemptResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Attempt       *ClaimedAttempt        `protobuf:"bytes,1,opt,name=attempt,proto3" json:"attempt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClaimNextAttemptResponse) Reset() {
	*x = ClaimNextAttemptResponse{}
	mi := &file_api_proto_mill_execution_v1_execution_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimNextAttemptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimNextAttemptResponse) ProtoMessage() {}

func (x *ClaimNextAttemptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_mill_execution_v1_execution_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimNextAttemptResponse.ProtoReflect.Descriptor instead.
func (*ClaimNextAttemptResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_mill_execution_v1_execution_proto_rawDescGZIP(), []int{3}
}

func (x *ClaimNextAttemptResponse) GetAttempt() *ClaimedAttempt {
	if x != nil {
		return x.Attempt
	}
	return nil
}

type MarkAttemptRunningRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AttemptId     string                 `protobuf:"bytes,1,opt,name=attempt_id,json=attemptId,proto3" json:"attempt_id,omitempty"`
	LeaseToken    string                 `protobuf:"bytes,2,opt,name=lease_token,json=leaseToken,proto3" json:"lease_token,omitempty"`
	ExternalId    string                 `protobuf:"bytes,3,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkAttemptRunningRequest) Reset() {
	*x = MarkAttemptRunningRequest{}
	mi := &file_api_proto_mill_execution_v1_execution_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkAttemptRunningRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkAttemptRunningRequest) ProtoMessage() {}

func (x *MarkAttemptRunningRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_mill_execution_v1_execution_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkAttemptRunningRequest.ProtoReflect.Descriptor instead.
func (*MarkAttemptRunningRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_mill_execution_v1_execution_proto_rawDescGZIP(), []int{4}
}

func (x *MarkAttemptRunningRequest) GetAttemptId() string {
	if x != nil {
		return x.AttemptId
	}
	return ""
}

func (x *MarkAttemptRunningRequest) GetLeaseToken() string {
	if x != nil {
		return x.LeaseToken
	}
	return ""
}

func (x *MarkAttemptRunningRequest) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

type CompleteAttemptRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AttemptId     string                 `protobuf:"bytes,1,opt,name=attempt_id,json=attemptId,proto3" json:"attempt_id,omitempty"`
	LeaseToken    string                 `protobuf:"bytes,2,opt,name=lease_token,json=leaseToken,proto3" json:"lease_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteAttemptRequest) Reset() {
	*x = CompleteAttemptRequest{}
	mi := &file_api_proto_mill_execution_v1_execution_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteAttemptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteAttemptRequest) ProtoMessage() {}

func (x *CompleteAttemptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_mill_execution_v1_execution_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteAttemptRequest.ProtoReflect.Descriptor instead.
func (*CompleteAttemptRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_mill_execution_v1_execution_proto_rawDescGZIP(), []int{5}
}

func (x *CompleteAttemptRequest) GetAttemptId() string {
	if x != nil {
		return x.AttemptId
	}
	return ""
}

func (x *CompleteAttemptRequest) GetLeaseToken() string {
	if x != nil {
		return x.LeaseToken
	}
	return ""
}

type FailAttemptRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AttemptId      string                 `protobuf:"bytes,1,opt,name=attempt_id,json=attemptId,proto3" json:"attempt_id,omitempty"`
	LeaseToken     string                 `protobuf:"bytes,2,opt,name=lease_token,json=leaseToken,proto3" json:"lease_token,omitempty"`
	FailureMessage string                 `protobuf:"bytes,3,opt,name=failure_message,json=failureMessage,proto3" json:"failure_message,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FailAttemptRequest) Reset() {
	*x = FailAttemptRequest{}
	mi := &file_api_proto_mill_execution_v1_execution_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FailAttemptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FailAttemptRequest) ProtoMessage() {}

func (x *FailAttemptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_mill_execution_v1_execution_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FailAttemptRequest.ProtoReflect.Descriptor instead.
func (*FailAttemptRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_mill_execution_v1_execution_proto_rawDescGZIP(), []int{6}
}

func (x *FailAttemptRequest) GetAttemptId() string {
	if x != nil {
		return x.AttemptId
	}
	return ""
}

func (x *FailAttemptRequest) GetLeaseToken() string {
	if x != nil {
		return x.LeaseToken
	}
	return ""
}

func (x *FailAttemptRequest) GetFailureMessage() string {
	if x != nil {
		return x.FailureMessage
	}
	return ""
}

type AttemptResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Attempt       *Attempt               `protobuf:"bytes,1,opt,name=attempt,proto3" json:"attempt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttemptResponse) Reset() {
	*x = AttemptResponse{}
	mi := &file_api_proto_mill_execution_v1_execution_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttemptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttemptResponse) ProtoMessage() {}

func (x *AttemptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_mill_execution_v1_execution_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttemptResponse.ProtoReflect.Descriptor instead.
func (*AttemptResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_mill_execution_v1_execution_proto_rawDescGZIP(), []int{7}
}

func (x *AttemptResponse) GetAttempt() *Attempt {
	if x != nil {
		return x.Attempt
	}
	return nil
}

type ClaimedAttempt struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Attempt        *Attempt               `protobuf:"bytes,1,opt,name=attempt,proto3" json:"attempt,omitempty"`
	Executable     *Executable            `protobuf:"bytes,2,opt,name=executable,proto3" json:"executable,omitempty"`
	ShardIndex     int32                  `protobuf:"varint,3,opt,name=shard_index,json=shardIndex,proto3" json:"shard_index,omitempty"`
	InputUri       string                 `protobuf:"bytes,4,opt,name=input_uri,json=inputUri,proto3" json:"input_uri,omitempty"`
	InputStartByte int64                  `protobuf:"varint,5,opt,name=input_start_byte,json=inputStartByte,proto3" json:"input_start_byte,omitempty"`
	InputEndByte   int64                  `protobuf:"varint,6,opt,name=input_end_byte,json=inputEndByte,proto3" json:"input_end_byte,omitempty"`
	OutputUri      string                 `protobuf:"bytes,7,opt,name=output_uri,json=outputUri,proto3" json:"output_uri,omitempty"`
	Resources      *Resources             `protobuf:"bytes,8,opt,name=resources,proto3" json:"resources,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ClaimedAttempt) Reset() {
	*x = ClaimedAttempt{}
	mi := &file_api_proto_mill_execution_v1_execution_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimedAttempt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimedAttempt) ProtoMessage() {}

func (x *ClaimedAttempt) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_mill_execution_v1_execution_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimedAttempt.ProtoReflect.Descriptor instead.
func (*ClaimedAttempt) Descriptor() ([]byte, []int) {
	return file_api_proto_mill_execution_v1_execution_proto_rawDescGZIP(), []int{8}
}

func (x *ClaimedAttempt) GetAttempt() *Attempt {
	if x != nil {
		return x.Attempt
	}
	return nil
}

func (x *ClaimedAttempt) GetExecutable() *Executable {
	if x != nil {
		return x.Executable
	}
	return nil
}

func (x *ClaimedAttempt) GetShardIndex() int32 {
	if x != nil {
		return x.ShardIndex
	}
	return 0
}

func (x *ClaimedAttempt) GetInputUri() string {
	if x != nil {
		return x.InputUri
	}
	return ""
}

func (x *ClaimedAttempt) GetInputStartByte() int64 {
	if x != nil {
		return x.InputStartByte
	}
	return 0
}

func (x *ClaimedAttempt) GetInputEndByte() int64 {
	if x != nil {
		return x.InputEndByte
	}
	return 0
}

func (x *ClaimedAttempt) GetOutputUri() string {
	if x != nil {
		return x.OutputUri
	}
	return ""
}

func (x *ClaimedAttempt) GetResources() *Resources {
	if x != nil {
		return x.Resources
	}
	return nil
}

type Resources struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	CpuRequestMillis   int64                  `protobuf:"varint,1,opt,name=cpu_request_millis,json=cpuRequestMillis,proto3" json:"cpu_request_millis,omitempty"`
	CpuLimitMillis     int64                  `protobuf:"varint,2,opt,name=cpu_limit_millis,json=cpuLimitMillis,proto3" json:"cpu_limit_millis,omitempty"`
	MemoryRequestBytes int64                  `protobuf:"varint,3,opt,name=memory_request_bytes,json=memoryRequestBytes,proto3" json:"memory_request_bytes,omitempty"`
	MemoryLimitBytes   int64                  `protobuf:"varint,4,opt,name=memory_limit_bytes,json=memoryLimitBytes,proto3" json:"memory_limit_bytes,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Resources) Reset() {
	*x = Resources{}
	mi := &file_api_proto_mill_execution_v1_execution_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resources) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resources) ProtoMessage() {}

func (x *Resources) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_mill_execution_v1_execution_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resources.ProtoReflect.Descriptor instead.
func (*Resources) Descriptor() ([]byte, []int) {
	return file_api_proto_mill_execution_v1_execution_proto_rawDescGZIP(), []int{9}
}

func (x *Resources) GetCpuRequestMillis() int64 {
	if x != nil {
		return x.CpuRequestMillis
	}
	return 0
}

func (x *Resources) GetCpuLimitMillis() int64 {
	if x != nil {
		return x.CpuLimitMillis
	}
	return 0
}

func (x *Resources) GetMemoryRequestBytes() int64 {
	if x != nil {
		return x.MemoryRequestBytes
	}
	return 0
}

func (x *Resources) GetMemoryLimitBytes() int64 {
	if x != nil {
		return x.MemoryLimitBytes
	}
	return 0
}

type Executable struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Image         string                 `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	Args          []string               `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Executable) Reset() {
	*x = Executable{}
	mi := &file_api_proto_mill_execution_v1_execution_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Executable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Executable) ProtoMessage() {}

func (x *Executable) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_mill_execution_v1_execution_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Executable.ProtoReflect.Descriptor instead.
func (*Executable) Descriptor() ([]byte, []int) {
	return file_api_proto_mill_execution_v1_execution_proto_rawDescGZIP(), []int{10}
}

func (x *Executable) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *Executable) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

type Attempt struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	JobId          string                 `protobuf:"bytes,2,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	TaskId         string                 `protobuf:"bytes,3,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Number         int32                  `protobuf:"varint,4,opt,name=number,proto3" json:"number,omitempty"`
	Executor       string                 `protobuf:"bytes,5,opt,name=executor,proto3" json:"executor,omitempty"`
	State          AttemptState           `protobuf:"varint,6,opt,name=state,proto3,enum=mill.execution.v1.AttemptState" json:"state,omitempty"`
	ExternalId     string                 `protobuf:"bytes,7,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	FailureMessage string                 `protobuf:"bytes,8,opt,name=failure_message,json=failureMessage,proto3" json:"failure_message,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	StartedAt      *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	FinishedAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=finished_at,json=finishedAt,proto3" json:"finished_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	LeaseOwner     string                 `protobuf:"bytes,13,opt,name=lease_owner,json=leaseOwner,proto3" json:"lease_owner,omitempty"`
	LeaseToken     string                 `protobuf:"bytes,14,opt,name=lease_token,json=leaseToken,proto3" json:"lease_token,omitempty"`
	LeaseExpiresAt *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=lease_expires_at,json=leaseExpiresAt,proto3" json:"lease_expires_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Attempt) Reset() {
	*x = Attempt{}
	mi := &file_api_proto_mill_execution_v1_execution_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Attempt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Attempt) ProtoMessage() {}

func (x *Attempt) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_mill_execution_v1_execution_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Attempt.ProtoReflect.Descriptor instead.
func (*Attempt) Descriptor() ([]byte, []int) {
	return file_api_proto_mill_execution_v1_execution_proto_rawDescGZIP(), []int{11}
}

func (x *Attempt) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Attempt) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *Attempt) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *Attempt) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *Attempt) GetExecutor() string {
	if x != nil {
		return x.Executor
	}
	return ""
}

func (x *Attempt) GetState() AttemptState {
	if x != nil {
		return x.State
	}
	return AttemptState_ATTEMPT_STATE_UNSPECIFIED
}

func (x *Attempt) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

func (x *Attempt) GetFailureMessage() string {
	if x != nil {
		return x.FailureMessage
	}
	return ""
}

func (x *Attempt) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Attempt) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *Attempt) GetFinishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FinishedAt
	}
	return nil
}

func (x *Attempt) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Attempt) GetLeaseOwner() string {
	if x != nil {
		return x.LeaseOwner
	}
	return ""
}

func (x *Attempt) GetLeaseToken() string {
	if x != nil {
		return x.LeaseToken
	}
	return ""
}

func (x *Attempt) GetLeaseExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LeaseExpiresAt
	}
	return nil
}

var File_api_proto_mill_execution_v1_execution_proto protoreflect.FileDescriptor

const file_api_proto_mill_execution_v1_execution_proto_rawDesc = "" +
	"\n" +
	"+api/proto/mill/execution/v1/execution.proto\x12\x11mill.execution.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"Y\n" +
	"\x1aLeaseActiveAttemptsRequest\x12\x1a\n" +
	"\bexecutor\x18\x01 \x01(\tR\bexecutor\x12\x1f\n" +
	"\vlease_owner\x18\x02 \x01(\tR\n" +
	"leaseOwner\"\\\n" +
	"\x1bLeaseActiveAttemptsResponse\x12=\n" +
	"\battempts\x18\x01 \x03(\v2!.mill.execution.v1.ClaimedAttemptR\battempts\"V\n" +
	"\x17ClaimNextAttemptRequest\x12\x1a\n" +
	"\bexecutor\x18\x01 \x01(\tR\bexecutor\x12\x1f\n" +
	"\vlease_owner\x18\x02 \x01(\tR\n" +
	"leaseOwner\"W\n" +
	"\x18ClaimNextAttemptResponse\x12;\n" +
	"\aattempt\x18\x01 \x01(\v2!.mill.execution.v1.ClaimedAttemptR\aattempt\"|\n" +
	"\x19MarkAttemptRunningRequest\x12\x1d\n" +
	"\n" +
	"attempt_id\x18\x01 \x01(\tR\tattemptId\x12\x1f\n" +
	"\vlease_token\x18\x02 \x01(\tR\n" +
	"leaseToken\x12\x1f\n" +
	"\vexternal_id\x18\x03 \x01(\tR\n" +
	"externalId\"X\n" +
	"\x16CompleteAttemptRequest\x12\x1d\n" +
	"\n" +
	"attempt_id\x18\x01 \x01(\tR\tattemptId\x12\x1f\n" +
	"\vlease_token\x18\x02 \x01(\tR\n" +
	"leaseToken\"}\n" +
	"\x12FailAttemptRequest\x12\x1d\n" +
	"\n" +
	"attempt_id\x18\x01 \x01(\tR\tattemptId\x12\x1f\n" +
	"\vlease_token\x18\x02 \x01(\tR\n" +
	"leaseToken\x12'\n" +
	"\x0ffailure_message\x18\x03 \x01(\tR\x0efailureMessage\"G\n" +
	"\x0fAttemptResponse\x124\n" +
	"\aattempt\x18\x01 \x01(\v2\x1a.mill.execution.v1.AttemptR\aattempt\"\xee\x02\n" +
	"\x0eClaimedAttempt\x124\n" +
	"\aattempt\x18\x01 \x01(\v2\x1a.mill.execution.v1.AttemptR\aattempt\x12=\n" +
	"\n" +
	"executable\x18\x02 \x01(\v2\x1d.mill.execution.v1.ExecutableR\n" +
	"executable\x12\x1f\n" +
	"\vshard_index\x18\x03 \x01(\x05R\n" +
	"shardIndex\x12\x1b\n" +
	"\tinput_uri\x18\x04 \x01(\tR\binputUri\x12(\n" +
	"\x10input_start_byte\x18\x05 \x01(\x03R\x0einputStartByte\x12$\n" +
	"\x0einput_end_byte\x18\x06 \x01(\x03R\finputEndByte\x12\x1d\n" +
	"\n" +
	"output_uri\x18\a \x01(\tR\toutputUri\x12:\n" +
	"\tresources\x18\b \x01(\v2\x1c.mill.execution.v1.ResourcesR\tresources\"\xc3\x01\n" +
	"\tResources\x12,\n" +
	"\x12cpu_request_millis\x18\x01 \x01(\x03R\x10cpuRequestMillis\x12(\n" +
	"\x10cpu_limit_millis\x18\x02 \x01(\x03R\x0ecpuLimitMillis\x120\n" +
	"\x14memory_request_bytes\x18\x03 \x01(\x03R\x12memoryRequestBytes\x12,\n" +
	"\x12memory_limit_bytes\x18\x04 \x01(\x03R\x10memoryLimitBytes\"6\n" +
	"\n" +
	"Executable\x12\x14\n" +
	"\x05image\x18\x01 \x01(\tR\x05image\x12\x12\n" +
	"\x04args\x18\x02 \x03(\tR\x04args\"\xf4\x04\n" +
	"\aAttempt\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x15\n" +
	"\x06job_id\x18\x02 \x01(\tR\x05jobId\x12\x17\n" +
	"\atask_id\x18\x03 \x01(\tR\x06taskId\x12\x16\n" +
	"\x06number\x18\x04 \x01(\x05R\x06number\x12\x1a\n" +
	"\bexecutor\x18\x05 \x01(\tR\bexecutor\x125\n" +
	"\x05state\x18\x06 \x01(\x0e2\x1f.mill.execution.v1.AttemptStateR\x05state\x12\x1f\n" +
	"\vexternal_id\x18\a \x01(\tR\n" +
	"externalId\x12'\n" +
	"\x0ffailure_message\x18\b \x01(\tR\x0efailureMessage\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"started_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12;\n" +
	"\vfinished_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"finishedAt\x129\n" +
	"\n" +
	"updated_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1f\n" +
	"\vlease_owner\x18\r \x01(\tR\n" +
	"leaseOwner\x12\x1f\n" +
	"\vlease_token\x18\x0e \x01(\tR\n" +
	"leaseToken\x12D\n" +
	"\x10lease_expires_at\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\x0eleaseExpiresAt*\x9b\x01\n" +
	"\fAttemptState\x12\x1d\n" +
	"\x19ATTEMPT_STATE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16ATTEMPT_STATE_STARTING\x10\x01\x12\x19\n" +
	"\x15ATTEMPT_STATE_RUNNING\x10\x02\x12\x1b\n" +
	"\x17ATTEMPT_STATE_COMPLETED\x10\x03\x12\x18\n" +
	"\x14ATTEMPT_STATE_FAILED\x10\x042\x99\x04\n" +
	"\x10ExecutionService\x12t\n" +
	"\x13LeaseActiveAttempts\x12-.mill.execution.v1.LeaseActiveAttemptsRequest\x1a..mill.execution.v1.LeaseActiveAttemptsResponse\x12k\n" +
	"\x10ClaimNextAttempt\x12*.mill.execution.v1.ClaimNextAttemptRequest\x1a+.mill.execution.v1.ClaimNextAttemptResponse\x12f\n" +
	"\x12MarkAttemptRunning\x12,.mill.execution.v1.MarkAttemptRunningRequest\x1a\".mill.execution.v1.AttemptResponse\x12`\n" +
	"\x0fCompleteAttempt\x12).mill.execution.v1.CompleteAttemptRequest\x1a\".mill.execution.v1.AttemptResponse\x12X\n" +
	"\vFailAttempt\x12%.mill.execution.v1.FailAttemptRequest\x1a\".mill.execution.v1.AttemptResponseBBZ@github.com/purinliang/mill/internal/execution/rpc/v1;executionv1b\x06proto3"

var (
	file_api_proto_mill_execution_v1_execution_proto_rawDescOnce sync.Once
	file_api_proto_mill_execution_v1_execution_proto_rawDescData []byte
)

func file_api_proto_mill_execution_v1_execution_proto_rawDescGZIP() []byte {
	file_api_proto_mill_execution_v1_execution_proto_rawDescOnce.Do(func() {
		file_api_proto_mill_execution_v1_execution_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_mill_execution_v1_execution_proto_rawDesc), len(file_api_proto_mill_execution_v1_execution_proto_rawDesc)))
	})
	return file_api_proto_mill_execution_v1_execution_proto_rawDescData
}

var file_api_proto_mill_execution_v1_execution_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_proto_mill_execution_v1_execution_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_api_proto_mill_execution_v1_execution_proto_goTypes = []any{
	(AttemptState)(0),                   // 0: mill.execution.v1.AttemptState
	(*LeaseActiveAttemptsRequest)(nil),  // 1: mill.execution.v1.LeaseActiveAttemptsRequest
	(*LeaseActiveAttemptsResponse)(nil), // 2: mill.execution.v1.LeaseActiveAttemptsResponse
	(*ClaimNextAttemptRequest)(nil),     // 3: mill.execution.v1.ClaimNextAttemptRequest
	(*ClaimNextAttemptResponse)(nil),    // 4: mill.execution.v1.ClaimNextAttemptResponse
	(*MarkAttemptRunningRequest)(nil),   // 5: mill.execution.v1.MarkAttemptRunningRequest
	(*CompleteAttemptRequest)(nil),      // 6: mill.execution.v1.CompleteAttemptRequest
	(*FailAttemptRequest)(nil),          // 7: mill.execution.v1.FailAttemptRequest
	(*AttemptResponse)(nil),             // 8: mill.execution.v1.AttemptResponse
	(*ClaimedAttempt)(nil),              // 9: mill.execution.v1.ClaimedAttempt
	(*Resources)(nil),                   // 10: mill.execution.v1.Resources
	(*Executable)(nil),                  // 11: mill.execution.v1.Executable
	(*Attempt)(nil),                     // 12: mill.execution.v1.Attempt
	(*timestamppb.Timestamp)(nil),       // 13: google.protobuf.Timestamp
}
var file_api_proto_mill_execution_v1_execution_proto_depIdxs = []int32{
	9,  // 0: mill.execution.v1.LeaseActiveAttemptsResponse.attempts:type_name -> mill.execution.v1.ClaimedAttempt
	9,  // 1: mill.execution.v1.ClaimNextAttemptResponse.attempt:type_name -> mill.execution.v1.ClaimedAttempt
	12, // 2: mill.execution.v1.AttemptResponse.attempt:type_name -> mill.execution.v1.Attempt
	12, // 3: mill.execution.v1.ClaimedAttempt.attempt:type_name -> mill.execution.v1.Attempt
	11, // 4: mill.execution.v1.ClaimedAttempt.executable:type_name -> mill.execution.v1.Executable
	10, // 5: mill.execution.v1.ClaimedAttempt.resources:type_name -> mill.execution.v1.Resources
	0,  // 6: mill.execution.v1.Attempt.state:type_name -> mill.execution.v1.AttemptState
	13, // 7: mill.execution.v1.Attempt.created_at:type_name -> google.protobuf.Timestamp
	13, // 8: mill.execution.v1.Attempt.started_at:type_name -> google.protobuf.Timestamp
	13, // 9: mill.execution.v1.Attempt.finished_at:type_name -> google.protobuf.Timestamp
	13, // 10: mill.execution.v1.Attempt.updated_at:type_name -> google.protobuf.Timestamp
	13, // 11: mill.execution.v1.Attempt.lease_expires_at:type_name -> google.protobuf.Timestamp
	1,  // 12: mill.execution.v1.ExecutionService.LeaseActiveAttempts:input_type -> mill.execution.v1.LeaseActiveAttemptsRequest
	3,  // 13: mill.execution.v1.ExecutionService.ClaimNextAttempt:input_type -> mill.execution.v1.ClaimNextAttemptRequest
	5,  // 14: mill.execution.v1.ExecutionService.MarkAttemptRunning:input_type -> mill.execution.v1.MarkAttemptRunningRequest
	6,  // 15: mill.execution.v1.ExecutionService.CompleteAttempt:input_type -> mill.execution.v1.CompleteAttemptRequest
	7,  // 16: mill.execution.v1.ExecutionService.FailAttempt:input_type -> mill.execution.v1.FailAttemptRequest
	2,  // 17: mill.execution.v1.ExecutionService.LeaseActiveAttempts:output_type -> mill.execution.v1.LeaseActiveAttemptsResponse
	4,  // 18: mill.execution.v1.ExecutionService.ClaimNextAttempt:output_type -> mill.execution.v1.ClaimNextAttemptResponse
	8,  // 19: mill.execution.v1.ExecutionService.MarkAttemptRunning:output_type -> mill.execution.v1.AttemptResponse
	8,  // 20: mill.execution.v1.ExecutionService.CompleteAttempt:output_type -> mill.execution.v1.AttemptResponse
	8,  // 21: mill.execution.v1.ExecutionService.FailAttempt:output_type -> mill.execution.v1.AttemptResponse
	17, // [17:22] is the sub-list for method output_type
	12, // [12:17] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_api_proto_mill_execution_v1_execution_proto_init() }
func file_api_proto_mill_execution_v1_execution_proto_init() {
	if File_api_proto_mill_execution_v1_execution_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_mill_execution_v1_execution_proto_rawDesc), len(file_api_proto_mill_execution_v1_execution_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_mill_execution_v1_execution_proto_goTypes,
		DependencyIndexes: file_api_proto_mill_execution_v1_execution_proto_depIdxs,
		EnumInfos:         file_api_proto_mill_execution_v1_execution_proto_enumTypes,
		MessageInfos:      file_api_proto_mill_execution_v1_execution_proto_msgTypes,
	}.Build()
	File_api_proto_mill_execution_v1_execution_proto = out.File
	file_api_proto_mill_execution_v1_execution_proto_goTypes = nil
	file_api_proto_mill_execution_v1_execution_proto_depIdxs = nil
}
