// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: api/proto/mill/execution/v1/execution.proto

package executionv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ExecutionService_LeaseActiveAttempts_FullMethodName = "/mill.execution.v1.ExecutionService/LeaseActiveAttempts"
	ExecutionService_ClaimNextAttempt_FullMethodName    = "/mill.execution.v1.ExecutionService/ClaimNextAttempt"
	ExecutionService_MarkAttemptRunning_FullMethodName  = "/mill.execution.v1.ExecutionService/MarkAttemptRunning"
	ExecutionService_CompleteAttempt_FullMethodName     = "/mill.execution.v1.ExecutionService/CompleteAttempt"
	ExecutionService_FailAttempt_FullMethodName         = "/mill.execution.v1.ExecutionService/FailAttempt"
)

// ExecutionServiceClient is the client API for ExecutionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ExecutionService is the internal boundary through which execution replicas
// lease work and report guarded state transitions to the Job service.
type ExecutionServiceClient interface {
	LeaseActiveAttempts(ctx context.Context, in *LeaseActiveAttemptsRequest, opts ...grpc.CallOption) (*LeaseActiveAttemptsResponse, error)
	ClaimNextAttempt(ctx context.Context, in *ClaimNextAttemptRequest, opts ...grpc.CallOption) (*ClaimNextAttemptResponse, error)
	MarkAttemptRunning(ctx context.Context, in *MarkAttemptRunningRequest, opts ...grpc.CallOption) (*AttemptResponse, error)
	CompleteAttempt(ctx context.Context, in *CompleteAttemptRequest, opts ...grpc.CallOption) (*AttemptResponse, error)
	FailAttempt(ctx context.Context, in *FailAttemptRequest, opts ...grpc.CallOption) (*AttemptResponse, error)
}

type executionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewExecutionServiceClient(cc grpc.ClientConnInterface) ExecutionServiceClient {
	return &executionServiceClient{cc}
}

func (c *executionServiceClient) LeaseActiveAttempts(ctx context.Context, in *LeaseActiveAttemptsRequest, opts ...grpc.CallOption) (*LeaseActiveAttemptsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LeaseActiveAttemptsResponse)
	err := c.cc.Invoke(ctx, ExecutionService_LeaseActiveAttempts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *executionServiceClient) ClaimNextAttempt(ctx context.Context, in *ClaimNextAttemptRequest, opts ...grpc.CallOption) (*ClaimNextAttemptResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClaimNextAttemptResponse)
	err := c.cc.Invoke(ctx, ExecutionService_ClaimNextAttempt_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *executionServiceClient) MarkAttemptRunning(ctx context.Context, in *MarkAttemptRunningRequest, opts ...grpc.CallOption) (*AttemptResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AttemptResponse)
	err := c.cc.Invoke(ctx, ExecutionService_MarkAttemptRunning_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *executionServiceClient) CompleteAttempt(ctx context.Context, in *CompleteAttemptRequest, opts ...grpc.CallOption) (*AttemptResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AttemptResponse)
	err := c.cc.Invoke(ctx, ExecutionService_CompleteAttempt_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *executionServiceClient) FailAttempt(ctx context.Context, in *FailAttemptRequest, opts ...grpc.CallOption) (*AttemptResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AttemptResponse)
	err := c.cc.Invoke(ctx, ExecutionService_FailAttempt_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExecutionServiceServer is the server API for ExecutionService service.
// All implementations must embed UnimplementedExecutionServiceServer
// for forward compatibility.
//
// ExecutionService is the internal boundary through which execution replicas
// lease work and report guarded state transitions to the Job service.
type ExecutionServiceServer interface {
	LeaseActiveAttempts(context.Context, *LeaseActiveAttemptsRequest) (*LeaseActiveAttemptsResponse, error)
	ClaimNextAttempt(context.Context, *ClaimNextAttemptRequest) (*ClaimNextAttemptResponse, error)
	MarkAttemptRunning(context.Context, *MarkAttemptRunningRequest) (*AttemptResponse, error)
	CompleteAttempt(context.Context, *CompleteAttemptRequest) (*AttemptResponse, error)
	FailAttempt(context.Context, *FailAttemptRequest) (*AttemptResponse, error)
	mustEmbedUnimplementedExecutionServiceServer()
}

// UnimplementedExecutionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedExecutionServiceServer struct{}

func (UnimplementedExecutionServiceServer) LeaseActiveAttempts(context.Context, *LeaseActiveAttemptsRequest) (*LeaseActiveAttemptsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LeaseActiveAttempts not implemented")
}
func (UnimplementedExecutionServiceServer) ClaimNextAttempt(context.Context, *ClaimNextAttemptRequest) (*ClaimNextAttemptResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ClaimNextAttempt not implemented")
}
func (UnimplementedExecutionServiceServer) MarkAttemptRunning(context.Context, *MarkAttemptRunningRequest) (*AttemptResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MarkAttemptRunning not implemented")
}
func (UnimplementedExecutionServiceServer) CompleteAttempt(context.Context, *CompleteAttemptRequest) (*AttemptResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CompleteAttempt not implemented")
}
func (UnimplementedExecutionServiceServer) FailAttempt(context.Context, *FailAttemptRequest) (*AttemptResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FailAttempt not implemented")
}
func (UnimplementedExecutionServiceServer) mustEmbedUnimplementedExecutionServiceServer() {}
func (UnimplementedExecutionServiceServer) testEmbeddedByValue()                          {}

// UnsafeExecutionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ExecutionServiceServer will
// result in compilation errors.
type UnsafeExecutionServiceServer interface {
	mustEmbedUnimplementedExecutionServiceServer()
}

func RegisterExecutionServiceServer(s grpc.ServiceRegistrar, srv ExecutionServiceServer) {
	// If the following call panics, it indicates UnimplementedExecutionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ExecutionService_ServiceDesc, srv)
}

func _ExecutionService_LeaseActiveAttempts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LeaseActiveAttemptsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExecutionServiceServer).LeaseActiveAttempts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExecutionService_LeaseActiveAttempts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExecutionServiceServer).LeaseActiveAttempts(ctx, req.(*LeaseActiveAttemptsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExecutionService_ClaimNextAttempt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClaimNextAttemptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExecutionServiceServer).ClaimNextAttempt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExecutionService_ClaimNextAttempt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExecutionServiceServer).ClaimNextAttempt(ctx, req.(*ClaimNextAttemptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExecutionService_MarkAttemptRunning_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarkAttemptRunningRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExecutionServiceServer).MarkAttemptRunning(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExecutionService_MarkAttemptRunning_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExecutionServiceServer).MarkAttemptRunning(ctx, req.(*MarkAttemptRunningRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExecutionService_CompleteAttempt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteAttemptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExecutionServiceServer).CompleteAttempt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExecutionService_CompleteAttempt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExecutionServiceServer).CompleteAttempt(ctx, req.(*CompleteAttemptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExecutionService_FailAttempt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FailAttemptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExecutionServiceServer).FailAttempt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExecutionService_FailAttempt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExecutionServiceServer).FailAttempt(ctx, req.(*FailAttemptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ExecutionService_ServiceDesc is the grpc.ServiceDesc for ExecutionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ExecutionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mill.execution.v1.ExecutionService",
	HandlerType: (*ExecutionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LeaseActiveAttempts",
			Handler:    _ExecutionService_LeaseActiveAttempts_Handler,
		},
		{
			MethodName: "ClaimNextAttempt",
			Handler:    _ExecutionService_ClaimNextAttempt_Handler,
		},
		{
			MethodName: "MarkAttemptRunning",
			Handler:    _ExecutionService_MarkAttemptRunning_Handler,
		},
		{
			MethodName: "CompleteAttempt",
			Handler:    _ExecutionService_CompleteAttempt_Handler,
		},
		{
			MethodName: "FailAttempt",
			Handler:    _ExecutionService_FailAttempt_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/mill/execution/v1/execution.proto",
}
